import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { CartContextProvider } from '@/context/CartContext';
import { Header } from '@/components/Header';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <CartContextProvider>
                    <div className="flex flex-col min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
                        <Header />
                        <main className="flex w-full flex-1">{children}</main>
                    </div>
                </CartContextProvider>
            </body>
        </html>
    );
}
